title: Devraj Priyadarshi
position: Undergraduate Student
affiliation: IIT, Kharagpur
email: devraj1priya@iitkgp.ac.in, devrajpriya01@gmail.com
keywords: minimal academic
github_link: https://github.com/devrajPriyadarshi
linkedin: https://www.linkedin.com/in/devraj-priyadarshi/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.jpg
favicon_dark: ./assets/img/favicon-dark.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
